module Awesomesauce
  Synonyms = [
    "alarming",
    "amazing",
    "astonishing",
    "awe-inspiring",
    "beautiful",
    "breathtaking",
    "really cool",
    "daunting",
    "exalted",
    "fantastic",
    "fearful",
    "formidable",
    "frantic",
    "grand",
    "imposing",
    "impressive",
    "incredible",
    "intimidating",
    "magnificent",
    "majestic",
    "marvelous",
    "mind-blowing",
    "overwhelming",
    "primo",
    "sensational",
    "shocking",
    "striking",
    "stunning",
    "wonderful",
    "wondrous",
  ]
end
